### PR TITLE
Actions to build artifacts

### PR DESCRIPTION
**Pull request by bergentroll**
Appends GitHub Actions workflow to build AZW3, EPUB, PDF files and upload its to releases. A release is created on every `git push` event.

:scroll: [Releases page](https://github.com/bergentroll/pali-english-recitations/releases).

:warning: It seems for me there is missing metadata (`META-INF/container.xml`) for EPUB file. So EPUB file has being buit, but Make `validate` and `optimize` targets fails and are not included to the workflow yet.

There is also some files' permissions changed: execution flag removed from non-executables.

### CODE REVIEW

**Comment by bergentroll** [comment]
It will be the link on a the latest PDF:
https://github.com/sasanarakkha/pali-english-recitations/releases/latest/download/SBS.Pali-English.Recitations.pdf

**Comment by paladhammika** [comment]
Sorry for the delay but nonetheless much gratitude and thanks @bergentroll for you contribution. This is quite nice since it saves the hassle of having to manually build for every new commit/addition to the chanting book.

I'll aim to address the EPUB metadata issues.

How to make the file names build with the filename "SBS Pāli-English Recitations.*" without any periods and with the diacritic "ā"?

**Comment by bergentroll** [comment]
@paladhammika 
Thank you, bhante Pāladhammika! :pray: Let it be useful.

> I'll aim to address the EPUB metadata issues.

Fine. I may add `validate` and `optimize` steps to the pipeline in such case.

> How to make the file names build with the filename "SBS Pāli-English Recitations.*" without any periods and with the diacritic "ā"?

It seems GitHub substitutes spaces with dots and purges diacritics because Latin filenames without spaces is most machine friendly.

Actually Make is also [not friendly to space char](https://stackoverflow.com/a/17969578/7486328), so e.g. `make epub` gives me `SBS\ Pāli-English\ Recitations.epub` with shielded spaces.

I see an option to put underscore `_` or dash `-` instead of periods and also use `aa` instead of the `ā` (it may be done with the pipeline).

**Comment by paladhammika** [comment]
Lets instead use dashes `-` instead of the periods as you suggested above. The "a" can remain as is.

**Comment by bergentroll** [comment]
Done in #12, bhante.

**Comment by paladhammika** [comment]
@bergentroll would you be willing to make this feature available for the *-patimokkha repositories in the sasanarakkha organization? Some of the documents will not build due to unresolved issues, this is not a problem.

**Comment by bergentroll** [comment]
@paladhammika, yes, bhante. With pleasure. But it may take some time (about few weeks) since I will be in a trip soon. :pray:

**Pull request merged**
